INSERT INTO characters (id, name) VALUES (0, 'Luigi');
INSERT INTO characters (id, name) VALUES (1, 'Mario');
INSERT INTO characters (id, name) VALUES (2, 'DK');
INSERT INTO characters (id, name) VALUES (3, 'Link');
INSERT INTO characters (id, name) VALUES (4, 'Samus');
INSERT INTO characters (id, name) VALUES (5, 'Falcon');
INSERT INTO characters (id, name) VALUES (6, 'Ness');
INSERT INTO characters (id, name) VALUES (7, 'Yoshi');
INSERT INTO characters (id, name) VALUES (8, 'Kirby');
INSERT INTO characters (id, name) VALUES (9, 'Fox');
INSERT INTO characters (id, name) VALUES (10, 'Pikachu');
INSERT INTO characters (id, name) VALUES (11, 'Jigglypuff');

INSERT INTO users (name, username, character_id) VALUES ('Neville', '@neville', 6);
INSERT INTO users (name, username, character_id) VALUES ('Jamie', '@jamie', 8);
INSERT INTO users (name, username, character_id) VALUES ('Chris', '@chris', 10);
INSERT INTO users (name, username, character_id) VALUES ('Guntars', '@guntars', 7);
INSERT INTO users (name, username, character_id) VALUES ('Erik', '@erik', 3);
INSERT INTO users (name, username, character_id) VALUES ('Mansi', '@mansi', 8);
INSERT INTO users (name, username, character_id) VALUES ('Eric', '@eric', 2);
INSERT INTO users (name, username, character_id) VALUES ('John', '@john', 1);
